# Generated by Django 3.0.3 on 2020-08-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0007_auto_20200824_2040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExtraFields',
        ),
    ]
