# Generated by Django 3.0.3 on 2020-08-24 16:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager_app', '0008_delete_userextrafields'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Manager',
        ),
    ]
