# Generated by Django 3.0.3 on 2020-08-25 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0011_auto_20200825_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the formet: '+999999999999'.up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
